In [1]:
import matplotlib.pyplot as plt
import numpy as np
import csv
import pandas as pd
from sklearn import linear_model
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("USA_Predictors_of_How_Counties_Vote.csv") 

In [3]:
print(df)

      Margin D  % Home Ownership  % Married Couples  % Poverty  \
0       -44.42           73.2906            67.0875    15.1852   
1       -53.76           75.2453            64.4356    10.3541   
2        -7.66           60.8989            50.9544    30.6687   
3       -57.73           74.4159            59.0777    18.1272   
4       -80.00           78.7787            68.7730    13.5515   
...        ...               ...                ...        ...   
3107    -50.63           76.2224            66.4696    11.4554   
3108     37.52           60.4058            58.2010     6.1497   
3109    -62.81           77.0567            73.9561    11.3431   
3110    -64.65           76.4933            67.9411    10.5055   
3111    -77.56           83.0163            69.0714    14.4731   

      % Bachelor's Degree or Higher  % Less than High School  \
0                           26.5716                  11.4834   
1                           31.8625                   9.1938   
2              

In [4]:
x=df.drop(["Margin D"],axis=1).values
y=df["Margin D"].values

In [5]:
print(y)

[-44.42 -53.76  -7.66 ... -62.81 -64.65 -77.56]


In [6]:
x_train,x_test,y_train,y_test,=train_test_split(x,y,test_size=0.2,random_state=0)

In [7]:
reg = linear_model.Ridge(alpha=.5)
reg.fit(x_train,y_train)

Ridge(alpha=0.5)

In [8]:
y_pred=reg.predict(x_test)
print(y_pred)

[ -30.87583558  -37.74640119  -45.17768708  -45.68683149  -57.2837535
  -59.04604948  -45.5029861   -41.15722284  -19.14206045  -36.05283763
  -64.3328757   -63.87356156  -53.69840476  -47.41267862  -31.39843864
   13.36843997  -56.35994861  -51.56009227  -31.52807692   10.51337468
  -13.82930588  -32.19192366  -47.9010192   -57.3227999   -72.37279658
   -8.03002984  -34.895742    -50.69648009  -12.96051907  -48.10515377
  -46.61451795  -11.28341039  -46.89437418  -10.11591358  -48.32791382
  -55.12862651  -44.84657878  -52.08170368  -28.11926627  -50.94636492
  -28.97338077  -79.99434449  -16.06607617  -43.95351542    9.80873605
  -20.39227684  -27.5893367   -36.01931394  -45.81226115  -51.65304137
  -36.5349503   -48.38627245  -53.22796494   -6.324371    -22.61360398
  -64.94640472  -12.96523818  -34.43589624  -18.8939155   -38.15863088
  -54.04901229    3.36257523  -41.11231039  -44.52898572   23.94369247
   -4.11732039  -34.44818017  -50.50059815  -54.20877609  -67.05000099
  -46.6

In [9]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.6835639321547539

In [10]:
# Wisconsin
HO=67.2
MC=60.8
PV=10.4
BD=31.3
DO=7.2
WT=80.8
BK=6.3
NA=0.8
AS=2.9
HS=7.1
FB=5.1


reg.predict([[HO,MC,PV,BD,DO,WT,BK,NA,AS,HS,FB]])

array([-11.74125434])

In [11]:
# Mississippi
HO=67.3
MC=54
PV=19.6
BD=22.3
DO=14.7
WT=56.3
BK=37.8
NA=0.4
AS=1
HS=3
FB=2.2

reg.predict([[HO,MC,PV,BD,DO,WT,BK,NA,AS,HS,FB]])

array([-4.61789574])

In [12]:
# California
HO=54.9
MC=60.7
PV=11.8
BD=35
DO=16
WT=36.3
BK=5.5
NA=0.4
AS=14.7
HS=39.4
FB=26.7

reg.predict([[HO,MC,PV,BD,DO,WT,BK,NA,AS,HS,FB]])

array([25.46925352])

In [13]:
# Massachusetts
HO=62.2
MC=59.4
PV=9.4
BD=45
DO=8.7
WT=70.3
BK=7.1
NA=0.2
AS=6.8
HS=12.4
FB=17.3

reg.predict([[HO,MC,PV,BD,DO,WT,BK,NA,AS,HS,FB]])

array([23.91462332])